### ISSUE TITLE
파일 경로를 못찾는 문제

### ISSUE THREAD

**Issue by neolabs120-mobile** [munsy0227/Chzzk-Rekoda#6]
안녕하세요. 치지직 라이브를 녹화할일이 있어 프로그램을 실행했는데 FileNotFoundError가 뜨더라구요. 디버깅을 해보니까 프로그램서 경로 자체를 못가져오길래 일단은 절대 경로를 지정하는 방식으로 해결은 했습니다만, 한번 살펴봐주시길 부탁드립니다. 환경은 Windows입니다.

Traceback (most recent call last):
  File "C:\Users\kamma\Chzzk-Rekoda\chzzk_record.py", line 161, in record_stream
    os.makedirs(output_dir, exist_ok=True)
  File "C:\Users\kamma\AppData\Local\Programs\Python\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] 지정된 경로를 찾을 수 없습니다: ''

**Comment by munsy0227** [comment]
우선 파일 저장 경로를 어떻게 하셨는지 알려주실 수 있을까요?

**Comment by neolabs120-mobile** [comment]
아 다시보니 제가 저장경로를 지정할때 그냥 엔터를 눌러 생긴 문제인것 같습니다. 건의드리자면 그냥 엔터를 누르면 기본적으로 스트리머 이름으로 경로를 기본적으로 지정해주는 기능이 있으면 편할것 같네요.
